service: rss

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1

package:
  include:
    - run.py

functions:
  rss:
    handler: run.naviny_rss
    events:
      - http:
          path: naviny
          method: get


